export { default as WalletAccountBermuda } from "./src/wallet-account-bermuda.js";
export type TypedDataDomain = import("ethers").TypedDataDomain;
export type TypedDataField = import("ethers").TypedDataField;
export type AuthorizationRequest = import("ethers").AuthorizationRequest;
export type Authorization = import("ethers").Authorization;
export type AuthorizationLike = import("ethers").AuthorizationLike;
export type EvmTransactionReceipt = import("ethers").TransactionReceipt;
export type FeeRates = import("@tetherto/wdk-wallet").FeeRates;
export type KeyPair = import("@tetherto/wdk-wallet").KeyPair;
export type TransactionResult = import("@tetherto/wdk-wallet").TransactionResult;
export type TransferResult = import("@tetherto/wdk-wallet").TransferResult;
export type TypedData = any;
export type DelegationInfo = any;
export type EvmTransaction = any;
export type EvmTransferOptions = any;
export type EvmWalletConfig = any;
export type BermudaSdk = import("@bermuda/sdk").ISdk;
export type BermudaKeyPair = import("@bermuda/sdk").KeyPair;
export type BermudaDepositOptions = import("@bermuda/sdk").IDepositOptions;
export type BermudaTransferOptions = import("@bermuda/sdk").ITransferOptions;
export type BermudaWithdrawOptions = import("@bermuda/sdk").IWithdrawOptions;
export type Payload = import("@bermuda/sdk").IPayload;
export type BermudaDepositParams = import("./src/wallet-account-bermuda.js").BermudaDepositParams;
export type BermudaTransferParams = import("./src/wallet-account-bermuda.js").BermudaTransferParams;
export type BermudaWithdrawParams = import("./src/wallet-account-bermuda.js").BermudaWithdrawParams;
export { default, default as WalletManagerBermuda } from "./src/wallet-manager-bermuda.js";
export { WalletAccountEvm, WalletAccountReadOnlyEvm } from "@tetherto/wdk-wallet-evm";
